"""
Django settings for SolarLQ project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config  # <-- أضف هذا السطر
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost').split(',')

# ==========================================================
# GROQ SETTINGS
# ==========================================================

import os

GROQ_API_KEY = config('GROQ_API_KEY') 

GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"

GROQ_MODEL = "llama-3.3-70b-versatile"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize', 
    'simulator',
    'accounts',
    'dashboard',
    'user_dashboard',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SolarLQ.urls'
CSRF_TRUSTED_ORIGINS = [
    "https://solaris-production-157c.up.railway.app",
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[BASE_DIR / 'templates', BASE_DIR / 'dashboard' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SolarLQ.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
import os

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'simulator/static'),
    os.path.join(BASE_DIR, 'accounts/static'),
    os.path.join(BASE_DIR, 'dashboard/static'),
    os.path.join(BASE_DIR, 'user_dashboard/static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.CustomUser'

# ========== إعدادات التخزين على Backblaze B2 ==========
import boto3
from botocore.config import Config

AWS_ACCESS_KEY_ID = config('B2_APPLICATION_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('B2_APPLICATION_KEY')
AWS_STORAGE_BUCKET_NAME = config('B2_BUCKET_NAME')

# هذا هو الرابط الخاص بدلو B2 (تأكد أنه مطابق للـ Endpoint في لوحة تحكم Backblaze)
AWS_S3_ENDPOINT_URL = 'https://s3.us-east-005.backblazeb2.com'
AWS_S3_REGION_NAME = 'us-east-005'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE = 'path'  # <-- هذا السطر السحري هو الحل!

# إعدادات إضافية لتحسين الاتصال ومنع الأخطاء
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = False
AWS_S3_VERIFT=True

# تخزين الميديا في B2
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.us-east-005.backblazeb2.com/"
# ========== تحسينات الأداء (Performance) ==========

# 1. ضغط الاستجابات (Gzip) - يقلل حجم الملفات المنقولة عبر الشبكة
MIDDLEWARE.insert(1, 'django.middleware.gzip.GZipMiddleware')

# 2. إعدادات الكاش (التخزين المؤقت) - يقلل الضغط على الخادم ويُسرّع الاستجابة
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-solaris-cache',
    }
}

# 3. جعل الملفات الثابتة تُخزّن في متصفح الزبون لمدة 30 يومًا
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ==========================
# Session & Cookie Settings
# ==========================

# تبقى الجلسة لمدة 30 يوم
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30

# لا تنتهي عند إغلاق المتصفح أو التطبيق
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# لأنك تستخدم HTTPS على Railway
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# يسمح بإرسال الكوكيز بشكل طبيعي
SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SAMESITE = "None"

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

SESSION_ENGINE = "django.contrib.sessions.backends.db"

# حفظ الجلسة بكل طلب
SESSION_SAVE_EVERY_REQUEST = True