# Generated by Django 4.2.30 on 2026-07-17 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quality', models.CharField(choices=[('economic', 'اقتصادي'), ('standard', 'متوسط'), ('premium', 'ممتاز')], default='standard', max_length=20)),
                ('package_image', django_resized.forms.ResizedImageField(crop=None, default='default/default_package.png', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[600, 400], upload_to='packages/')),
                ('inverter_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('battery_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_panel_power', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('daily_production', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_installment_available', models.BooleanField(default=False)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('promotion_request', models.BooleanField(default=False)),
                ('promotion_receipt', models.ImageField(blank=True, null=True, upload_to='promotion_receipts/')),
                ('promotion_end_date', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_promoted', '-rating', '-orders_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('panel', 'لوح شمسي'), ('inverter', 'انفرتر'), ('battery', 'بطارية'), ('structure', 'هياكل'), ('accessory', 'ملحقات')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('power_watt', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('battery_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('battery_type', models.CharField(blank=True, default='', max_length=50)),
                ('inverter_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('warranty_years', models.PositiveIntegerField(default=1)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='العدد')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_components', to='dashboard.solarpackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('status', models.CharField(choices=[('pending', '🟡 قيد المراجعة والتدقيق الأولي'), ('survey', '👨\u200d🔧 جاري الكشف الموقعي الفني'), ('preparing', '🟠 جاري تجهيز المواد والشحن'), ('on_way', '🔵 فريق التركيب في الطريق للموقع'), ('completed', '🟢 تم التشغيل والتسليم المعتمد'), ('canceled', '🔴 ملغي')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('payment_method', models.CharField(choices=[('cash', 'دفع نقدي (كاش) 💵'), ('installment', 'نظام الأقساط 💳')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الأساسي للباقة ($)')),
                ('extra_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='مصاريف إضافية بعد الكشف ($)')),
                ('extra_fees_reason', models.TextField(blank=True, null=True, verbose_name='سبب المصاريف الإضافية')),
                ('is_offline_sale', models.BooleanField(default=False, verbose_name='مبيع أوفلاين (بدون تركيب ميداني)')),
                ('purchased_items', models.CharField(blank=True, max_length=255, null=True, verbose_name='تفاصيل المشتريات المفردة')),
                ('survey_fee_iqd', models.IntegerField(default=0, verbose_name='رسوم الكشف الموقعي (0 = مجاني)')),
                ('is_survey_fee_paid', models.BooleanField(default=True, verbose_name='تمت تسوية الكشف')),
                ('is_customer_approved_fees', models.BooleanField(default=True, verbose_name='موافقة الزبون على الإضافات')),
                ('installation_address', models.TextField(blank=True, null=True, verbose_name='عنوان التركيب بالتفصيل')),
                ('gps_location_url', models.URLField(blank=True, null=True, verbose_name='رابط الموقع (GPS)')),
                ('survey_date', models.DateTimeField(blank=True, null=True, verbose_name='موعد الزيارة')),
                ('load_calculation', models.TextField(blank=True, null=True, verbose_name='حساب الأحمال والقدرة (AI)')),
                ('technical_report', models.TextField(blank=True, null=True, verbose_name='التقرير الهندسي للموقع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الزبون')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to=settings.AUTH_USER_MODEL, verbose_name='الشركة المنفذة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_orders', to=settings.AUTH_USER_MODEL, verbose_name='الزبون')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.solarpackage', verbose_name='الباقة المطلوبة')),
            ],
            options={
                'verbose_name': 'طلب زبون',
                'verbose_name_plural': 'إدارة الطلبات (CRM)',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_payment_paid', models.BooleanField(default=False, verbose_name='هل تم دفع المقدمة؟')),
                ('total_months', models.PositiveIntegerField(verbose_name='إجمالي أشهر السداد')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ القسط الشهري ($)')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تم تسديد كافة الأقساط ✅')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='dashboard.order', verbose_name='الطلب المرتبط')),
            ],
            options={
                'verbose_name': 'خطة تقسيط',
                'verbose_name_plural': 'خطط الأقساط والتمويل',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.PositiveIntegerField(verbose_name='رقم القسط (الشهر)')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المستحق')),
                ('status', models.CharField(choices=[('pending', '⏳ قيد الانتظار'), ('paid', '✅ تم الدفع'), ('late', '🚨 متأخر')], default='pending', max_length=15, verbose_name='حالة الدفع')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع الفعلي')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dashboard.installmentplan', verbose_name='خطة التقسيط')),
            ],
            options={
                'verbose_name': 'دفعة قسط',
                'verbose_name_plural': 'دفعات الأقساط الشهرية',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='DigitalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panels_serial', models.TextField(blank=True, null=True, verbose_name='سيريالات الألواح')),
                ('panels_warranty', models.IntegerField(default=10)),
                ('batteries_serial', models.TextField(blank=True, null=True, verbose_name='سيريالات البطاريات')),
                ('batteries_warranty', models.IntegerField(default=1)),
                ('inverter_serial', models.CharField(blank=True, max_length=255, null=True, verbose_name='سيريال العاكس')),
                ('inverter_warranty', models.IntegerField(default=1)),
                ('legal_terms', models.TextField()),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='contracts/pdfs/', verbose_name='ملف العقد (PDF)')),
                ('customer_signature', models.ImageField(blank=True, null=True, upload_to='contracts/signatures/', verbose_name='توقيع الزبون الرقمي')),
                ('panel_warranty_years', models.PositiveIntegerField(default=10, verbose_name='ضمان الألواح (سنوات)')),
                ('battery_warranty_years', models.PositiveIntegerField(default=1, verbose_name='ضمان البطاريات (سنوات)')),
                ('inverter_warranty_years', models.PositiveIntegerField(default=1, verbose_name='ضمان العاكس (سنوات)')),
                ('terms_and_conditions', models.TextField(default='يخضع هذا العقد لشروط وأحكام الصيانة والضمان المحددة من قبل الشركة المنفذة...', verbose_name='الشروط والأحكام القانونية')),
                ('issued_at', models.DateField(auto_now_add=True, verbose_name='تاريخ إصدار العقد')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='dashboard.order', verbose_name='الطلب المرتبط')),
            ],
            options={
                'verbose_name': 'عقد وضمان رقمي',
                'verbose_name_plural': 'العقود والضمانات الرقمية',
            },
        ),
        migrations.CreateModel(
            name='CompletedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المشروع (مثال: تركيب منظومة 10 أمبير في المنصور)')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('main_image', models.ImageField(upload_to='portfolio/projects/', verbose_name='صورة المشروع الحية')),
                ('location', models.CharField(max_length=255, verbose_name='موقع التنفيذ (المدينة/المنطقة)')),
                ('customer_feedback', models.TextField(blank=True, null=True, verbose_name='رأي وتقييم الزبون')),
                ('completion_date', models.DateField(verbose_name='تاريخ إنجاز المشروع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to=settings.AUTH_USER_MODEL, verbose_name='الشركة المنفذة')),
                ('package_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.solarpackage', verbose_name='الباقة التي تم تركيبها')),
            ],
            options={
                'verbose_name': 'مشروع منجز',
                'verbose_name_plural': 'معرض المشاريع الحية',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='company_covers/', verbose_name='صورة الغلاف')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='نبذة عن الشركة')),
                ('support_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف الدعم الفني')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الواتساب (للإشعارات والربط)')),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='ساعات العمل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف الشركة',
                'verbose_name_plural': 'ملفات الشركات',
            },
        ),
    ]
