# Generated by Django 4.2.30 on 2026-07-17 15:19

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('accepted_terms', models.BooleanField(default=False, verbose_name='موافق على الشروط')),
                ('user_type', models.CharField(choices=[('user', 'User'), ('company', 'Company')], default='user', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('governorate', models.CharField(choices=[('بغداد', 'بغداد'), ('نينوى', 'نينوى'), ('البصرة', 'البصرة'), ('أربيل', 'أربيل'), ('النجف', 'النجف'), ('كربلاء', 'كربلاء'), ('ذي قار', 'ذي قار'), ('بابل', 'بابل'), ('السليمانية', 'السليمانية'), ('دهوك', 'دهوك'), ('كركوك', 'كركوك'), ('صلاح الدين', 'صلاح الدين'), ('الانبار', 'الانبار'), ('ديالى', 'ديالى'), ('المثنى', 'المثنى'), ('القادسية', 'القادسية'), ('واسط', 'واسط'), ('ميسان', 'ميسان')], default='بغداد', max_length=50, verbose_name='المحافظة')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان التفصيلي')),
                ('gps_coordinates', models.CharField(blank=True, max_length=100, null=True, verbose_name='إحداثيات الموقع (GPS)')),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[600, 400], upload_to='company_logos/')),
                ('commercial_license', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[600, 400], upload_to='commercial_licenses/')),
                ('is_approved', models.BooleanField(default=False, verbose_name='حالة الموافقة (للشركات)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
