# Generated by Django 4.2.30 on 2026-06-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='company_logo',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
