# Generated by Django 4.2.30 on 2026-07-17 15:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='commercial_license',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[600, 400], upload_to='commercial_licenses/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[600, 400], upload_to='company_logos/'),
        ),
    ]
