# Generated by Django 4.2.30 on 2026-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_company_description_customuser_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commercial_license',
            field=models.ImageField(blank=True, null=True, upload_to='commercial_licenses/'),
        ),
    ]
