# Generated by Django 4.2.17 on 2026-06-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='governorate',
            field=models.CharField(choices=[('بغداد', 'بغداد'), ('نينوى', 'نينوى'), ('البصرة', 'البصرة'), ('أربيل', 'أربيل'), ('النجف', 'النجف'), ('كربلاء', 'كربلاء'), ('ذي قار', 'ذي قار'), ('بابل', 'بابل'), ('السليمانية', 'السليمانية'), ('دهوك', 'دهوك'), ('كركوك', 'كركوك'), ('صلاح الدين', 'صلاح الدين'), ('الانبار', 'الانبار'), ('ديالى', 'ديالى'), ('المثنى', 'المثنى'), ('القادسية', 'القادسية'), ('واسط', 'واسط'), ('ميسان', 'ميسان')], default='بغداد', max_length=50, verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gps_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='إحداثيات الموقع (GPS)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان التفصيلي'),
        ),
    ]
