# Generated by Django 4.2.17 on 2026-07-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_governorate_customuser_gps_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_terms',
            field=models.BooleanField(default=False, verbose_name='موافق على الشروط'),
        ),
    ]
