# Generated by Django 4.2.17 on 2026-07-02 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المقال أو النصيحة')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wiki_images/', verbose_name='صورة توضيحية')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشور؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='dashboard.solarpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('inspection', 'كشف موقعي'), ('maintenance', 'صيانة أعطال'), ('washing', 'تنظيف ألواح')], max_length=20, verbose_name='نوع الخدمة')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل المشكلة أو الطلب')),
                ('location_details', models.CharField(max_length=255, verbose_name='العنوان بالتفصيل (أو القرية)')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='التاريخ المفضل للزيارة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'تم القبول'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('company', models.ForeignKey(limit_choices_to={'user_type': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.solarpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم الحسبة (مثلاً: بيتي، المحل، المزرعة)')),
                ('total_kwh_day', models.FloatField(default=0.0, verbose_name='إجمالي الاستهلاك اليومي (كيلوواط/ساعة)')),
                ('max_surge_watts', models.IntegerField(default=0, verbose_name='أعلى لود إقلاع لحظي (واط)')),
                ('appliances_data', models.JSONField(help_text='يحفظ الأجهزة بصيغة JSON', verbose_name='تفاصيل الأجهزة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_calculators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='التقييم (1-5 نجوم)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(limit_choices_to={'user_type': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeasibilityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_electricity_bill', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ai_reason', models.TextField()),
                ('estimated_monthly_generation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_yearly_generation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('co2_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_daily_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_saving', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yearly_saving', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payback_years', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_profit_25_years', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_text', models.TextField(blank=True, default='')),
                ('calculator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_dashboard.savedcalculator')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.solarpackage')),
                ('recommended_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feasibility_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(blank=True, null=True, verbose_name='رسالة المستخدم')),
                ('ai_response', models.TextField(verbose_name='رد الذكاء الاصطناعي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_title', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
