# Generated by Django 4.2.17 on 2026-07-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeasibilityReport',
        ),
    ]
