# Generated by Django 4.2.17 on 2026-07-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_delete_feasibilityreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcalculator',
            name='is_used',
        ),
    ]
