# Generated by Django 4.2.17 on 2026-07-07 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_dashboard', '0003_remove_savedcalculator_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='محادثة جديدة', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'محادثة الذكاء الاصطناعي',
                'verbose_name_plural': 'محادثات الذكاء الاصطناعي',
                'ordering': ['-is_pinned', '-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'المستخدم'), ('assistant', 'الذكاء الاصطناعي'), ('system', 'النظام')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('response_time', models.FloatField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_dashboard.aiconversation')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('image', 'صورة'), ('file', 'ملف'), ('audio', 'صوت')], max_length=20)),
                ('file', models.FileField(upload_to='ai_assistant/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='user_dashboard.aimessage')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'مرفقات الرسائل',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
