# Generated by Django 4.2.17 on 2026-07-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_aiconversation_aimessage_aiattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimessage',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='aimessage',
            name='is_error',
        ),
        migrations.RemoveField(
            model_name='aimessage',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='aimessage',
            name='response_time',
        ),
        migrations.RemoveField(
            model_name='aimessage',
            name='tokens_used',
        ),
        migrations.DeleteModel(
            name='AIAttachment',
        ),
    ]
