# Generated by Django 4.2.17 on 2026-07-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_remove_aimessage_error_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimessage',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='aimessage',
            name='is_edited',
        ),
        migrations.DeleteModel(
            name='AIChatHistory',
        ),
    ]
